/* SideBar */
export const SIDEBAR_HIDDEN = '[SIDEBAR_HIDDEN]'
export const SIDEBAR_TOGGLE = '[SIDEBAR_TOGGLE]'
export const SIDEBAR_SHOW = '[SIDEBAR_SHOW]'
export const SIDEBAR_GHOST = '[SIDEBAR_GHOST]'
export const SIDEBAR_STATIC = '[SIDEBAR_STATIC]'

/* Wizard Form */
export const WIZARD_INIT = '[WIZARD_INIT]'
export const WIZARD_CLEAR = '[WIZARD_CLEAR]'
export const WIZARD_NEXT = '[WIZARD_NEXT]'
export const WIZARD_PREV = '[WIZARD_PREV]'
export const WIZARD_GOTO_ENTERED = '[WIZARD_GOTO_ENTERED]'
export const WIZARD_SUBMITED = '[WIZARD_SUBMITED]'
export const WIZARD_LOADING_START = '[WIZARD_LOADING_START]'
export const WIZARD_LOADING_FINISHED = '[WIZARD_LOADING_FINISHED]'
export const WIZARD_UPDATE_FORM_VALUE = '[WIZARD_UPDATE_FORM_VALUE]'
export const WIZARD_CLEAR_FORM_VALUE = '[WIZARD_CLEAR_FORM_VALUE]'
